version: "3.9"

services:
  backend:
    image: amakye94/careplus-backend:latest
    container_name: careplus-backend
    ports:
      - "8000:8000"
    networks:
      - careplus-net
    environment:
      - ENV=production
    restart: always
    command: >
      uvicorn backend.main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: amakye94/careplus-frontend:latest   # optional: tag & push later
    container_name: careplus-frontend
    ports:
      - "8080:80"      # <-- use 8080 so it does not conflict with WSL port 80
    depends_on:
      - backend
    networks:
      - careplus-net
    restart: always

networks:
  careplus-net:
    driver: bridge
