services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: careplus-backend
    ports:
      - "8000:8000"
    networks:
      - careplus-net

  frontend:
    build:
      context: frontend
    container_name: careplus-frontend
    ports:
      - "8080:80"
    networks:
      - careplus-net

networks:
  careplus-net:
